// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGFP.Infrastructure.Context;

#nullable disable

namespace SGFP.Infrastructure.Migrations
{
    [DbContext(typeof(AppSGPFContext))]
    [Migration("20251220131723_init01")]
    partial class init01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SGFP.Domain.Entities.TB001Categoria", b =>
                {
                    b.Property<int>("categoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoriaId"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME");

                    b.Property<bool>("status")
                        .HasColumnType("bit")
                        .HasColumnName("STATUS");

                    b.HasKey("categoriaId");

                    b.ToTable("TB001_CATEGORIA", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.Tb002ItemListaCompra", b =>
                {
                    b.Property<int>("itemListaCompra_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ITEM_LISTA_COMPRA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("itemListaCompra_Id"));

                    b.Property<int>("categoria_Id")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIA_ID");

                    b.Property<DateTime>("data_Compra_Produtos")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA_COMPRA_PRODUTOS");


                    b.Property<string>("nome_Produto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME_PRODUTO");

                    b.Property<int>("quantidade_Produto")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE_PRODUTO");

                    b.Property<double>("sub_Total_Produtos")
                        .HasColumnType("double precision")
                        .HasColumnName("SUB_TOTAL_PRODUTOS");

                    b.Property<int>("usuario_Id")
                        .HasColumnType("int")
                        .HasColumnName("USUARIO_ID");

                    b.Property<double>("valor_Unitario")
                        .HasColumnType("double precision")
                        .HasColumnName("VALOR_UNITARIO");

                    b.HasKey("itemListaCompra_Id");

                    b.HasIndex("categoria_Id");

                    b.ToTable("TB002_ITEM_LISTA_COMPRA", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.Tb002ItemListaCompra", b =>
                {
                    b.HasOne("SGFP.Domain.Entities.TB001Categoria", "TB001Categoria")
                        .WithMany("Tb002ItemListaCompra")
                        .HasForeignKey("categoria_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TB001Categoria");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB001Categoria", b =>
                {
                    b.Navigation("Tb002ItemListaCompra");
                });
#pragma warning restore 612, 618
        }
    }
}
