// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGFP.Infrastructure.Context;

#nullable disable

namespace SGFP.Infrastructure.Migrations
{
    [DbContext(typeof(AppSGPFContext))]
    [Migration("20251226023143_init05")]
    partial class init05
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SGFP.Domain.Entities.TB001Categoria", b =>
                {
                    b.Property<int>("categoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoriaId"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME");

                    b.Property<bool>("status")
                        .HasColumnType("bit")
                        .HasColumnName("STATUS");

                    b.HasKey("categoriaId");

                    b.ToTable("TB001_CATEGORIA", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB003_Categoria_Receita", b =>
                {
                    b.Property<int>("categoriaReceita_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIA_RECEITA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoriaReceita_Id"));

                    b.Property<string>("categoriaReceita_Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CATEGORIA_RECEITA_NOME");

                    b.HasKey("categoriaReceita_Id");

                    b.ToTable("TB003_CATEGORIA_RECEITA", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB004_Tipo_Origem_Dinheiro", b =>
                {
                    b.Property<int>("tipoOrigemDinheiro_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TIPO_ORIGEM_DINHEIRO_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tipoOrigemDinheiro_Id"));

                    b.Property<int>("categoriaReceita_Id")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIA_RECEITA_ID");

                    b.Property<string>("tipo_Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TIPO_DESCRICAO");

                    b.Property<string>("tipo_Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TIPO_NOME");

                    b.HasKey("tipoOrigemDinheiro_Id");

                    b.HasIndex("categoriaReceita_Id");

                    b.ToTable("TB004_TIPO_ORIGEM_DINHEIRO", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB005_Recebimento", b =>
                {
                    b.Property<int>("recebimento_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RECEBIMENTO_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("recebimento_Id"));

                    b.Property<string>("recebimento_Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RECEBIMENTO_DESCRICAO");

                    b.Property<string>("recebimento_Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RECEBIMENTO_NOME");

                    b.HasKey("recebimento_Id");

                    b.ToTable("TB005_RECEBIMENTO", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB006_Frequencia", b =>
                {
                    b.Property<int>("frequencia_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FREQUENCIA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("frequencia_Id"));

                    b.Property<string>("frequencia_Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FREQUENCIA_DESCRICAO");

                    b.Property<string>("frequencia_Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FREQUENCIA_NOME");

                    b.HasKey("frequencia_Id");

                    b.ToTable("TB006_FREQUENCIA", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB007_Receita", b =>
                {
                    b.Property<int>("receita_Id")
                        .HasColumnType("int")
                        .HasColumnName("RECEITA_ID");

                    b.Property<int>("categoriaReceita_Id")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIA_RECEITA_ID");

                    b.Property<int>("frequencia_Id")
                        .HasColumnType("int");

                    b.Property<int>("recebimento_Id")
                        .HasColumnType("int")
                        .HasColumnName("RECEBIMENTO_ID");

                    b.Property<decimal>("receita_Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("RECEITA_VALOR");

                    b.Property<int>("usuario_Id")
                        .HasColumnType("int")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("receita_Id");

                    b.HasIndex("frequencia_Id");

                    b.HasIndex("recebimento_Id");

                    b.ToTable("TB007_RECEITA", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB008_Categoria_Despesa", b =>
                {
                    b.Property<int>("categoria_Despesa_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIA_DESPESA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoria_Despesa_Id"));

                    b.Property<string>("categoria_Despesa_Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CATEGORIA_DESPESA_DESCRICAO");

                    b.Property<string>("categoria_Despesa_Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CATEGORIA_DESPESA_NOME");

                    b.HasKey("categoria_Despesa_Id");

                    b.ToTable("TB008_CATEGORIA_DESPESA", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB009_Tipo_Despesa", b =>
                {
                    b.Property<int>("tipo_Despesa_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TIPO_DESPESA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tipo_Despesa_Id"));

                    b.Property<int>("categoria_Despesa_Id")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIA_DESPESA_ID");

                    b.Property<string>("tipo_Despesa_Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TIPO_DESPESA_NOME");

                    b.HasKey("tipo_Despesa_Id");

                    b.HasIndex("categoria_Despesa_Id");

                    b.ToTable("TB009_TIPO_DESPESA", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB010_Despesa", b =>
                {
                    b.Property<int>("despesa_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DESPESA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("despesa_Id"));

                    b.Property<int>("categoria_Despesa_Id")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIA_DESPESA_ID");

                    b.Property<DateTime>("data_Vencimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_VENCIMENTO");

                    b.Property<string>("despesa_Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DESPESA_DESCRICAO");

                    b.Property<decimal>("despesa_Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DESPESA_VALOR");

                    b.Property<int>("usuario_Id")
                        .HasColumnType("int")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("despesa_Id");

                    b.HasIndex("categoria_Despesa_Id");

                    b.ToTable("TB010_DESPESA", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB011_Categoria_Produto_Compra", b =>
                {
                    b.Property<int>("categoria_Produto_Compra_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIA_PRODUTO_COMPRA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoria_Produto_Compra_ID"));

                    b.Property<string>("categoria_Produto_Compra_Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CATEGORIA_PRODUTO_COMPRA_NOME");

                    b.HasKey("categoria_Produto_Compra_ID");

                    b.ToTable("TB011_CATEGORIA_PRODUTO_COMPRA", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB012_Unidade_Produto_Compra", b =>
                {
                    b.Property<int>("unidadde_Produto_Compra_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UNIDADE_PRODUTO_COMPRA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("unidadde_Produto_Compra_Id"));

                    b.Property<string>("unidade_Produto_Compra_Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UNIDADE_PRODUTO_COMPRA_NOME");

                    b.HasKey("unidadde_Produto_Compra_Id");

                    b.ToTable("TB012_UNIDADE_PRODUTO_COMPRA", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB013_Item_Produto_Compra", b =>
                {
                    b.Property<int>("item_Produto_Compra_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ITEM_PRODUTO_COMPRA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("item_Produto_Compra_Id"));

                    b.Property<int>("categoria_Produto_Compra_ID")
                        .HasColumnType("int");

                    b.Property<string>("item_Produto_Compra_Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ITEM_PRODUTO_COMPRA_NOME");

                    b.HasKey("item_Produto_Compra_Id");

                    b.HasIndex("categoria_Produto_Compra_ID");

                    b.ToTable("TB013_ITEM_PRODUTO_COMPRA", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.Tb002ItemListaCompra", b =>
                {
                    b.Property<int>("itemListaCompra_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ITEM_LISTA_COMPRA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("itemListaCompra_Id"));

                    b.Property<int>("categoria_Id")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIA_ID");

                    b.Property<DateTime>("data_Compra_Produtos")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA_COMPRA_PRODUTOS");

                    b.Property<string>("nome_Produto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME_PRODUTO");

                    b.Property<int>("quantidade_Produto")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE_PRODUTO");

                    b.Property<double>("sub_Total_Produtos")
                        .HasColumnType("double precision")
                        .HasColumnName("SUB_TOTAL_PRODUTOS");

                    b.Property<int>("usuario_Id")
                        .HasColumnType("int")
                        .HasColumnName("USUARIO_ID");

                    b.Property<double>("valor_Unitario")
                        .HasColumnType("double precision")
                        .HasColumnName("VALOR_UNITARIO");

                    b.HasKey("itemListaCompra_Id");

                    b.HasIndex("categoria_Id");

                    b.ToTable("TB002_ITEM_LISTA_COMPRA", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB004_Tipo_Origem_Dinheiro", b =>
                {
                    b.HasOne("SGFP.Domain.Entities.TB003_Categoria_Receita", "TB003_Categoria_Receita")
                        .WithMany("TB004_Tipo_Origem_Dinheiros")
                        .HasForeignKey("categoriaReceita_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TB003_Categoria_Receita");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB007_Receita", b =>
                {
                    b.HasOne("SGFP.Domain.Entities.TB006_Frequencia", "TB006_Frequencias")
                        .WithMany("TB007_Receitas")
                        .HasForeignKey("frequencia_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGFP.Domain.Entities.TB005_Recebimento", "TB005_Recebimentos")
                        .WithMany("TB007_Receitas")
                        .HasForeignKey("recebimento_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGFP.Domain.Entities.TB003_Categoria_Receita", "TB003_Categoria_Receitas")
                        .WithMany("T007_Receitas")
                        .HasForeignKey("receita_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TB003_Categoria_Receitas");

                    b.Navigation("TB005_Recebimentos");

                    b.Navigation("TB006_Frequencias");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB009_Tipo_Despesa", b =>
                {
                    b.HasOne("SGFP.Domain.Entities.TB008_Categoria_Despesa", "TB008_Categoria_Despesas")
                        .WithMany("TB009_Tipo_Despesa")
                        .HasForeignKey("categoria_Despesa_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TB008_Categoria_Despesas");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB010_Despesa", b =>
                {
                    b.HasOne("SGFP.Domain.Entities.TB008_Categoria_Despesa", "TB008_Categoria_Despesas")
                        .WithMany("TB011_Despesas")
                        .HasForeignKey("categoria_Despesa_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TB008_Categoria_Despesas");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB013_Item_Produto_Compra", b =>
                {
                    b.HasOne("SGFP.Domain.Entities.TB011_Categoria_Produto_Compra", "TB011_Categoria_Produto_Compras")
                        .WithMany("TB013_Item_Produto_Compras")
                        .HasForeignKey("categoria_Produto_Compra_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TB011_Categoria_Produto_Compras");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.Tb002ItemListaCompra", b =>
                {
                    b.HasOne("SGFP.Domain.Entities.TB001Categoria", "TB001Categoria")
                        .WithMany("Tb002ItemListaCompra")
                        .HasForeignKey("categoria_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TB001Categoria");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB001Categoria", b =>
                {
                    b.Navigation("Tb002ItemListaCompra");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB003_Categoria_Receita", b =>
                {
                    b.Navigation("T007_Receitas");

                    b.Navigation("TB004_Tipo_Origem_Dinheiros");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB005_Recebimento", b =>
                {
                    b.Navigation("TB007_Receitas");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB006_Frequencia", b =>
                {
                    b.Navigation("TB007_Receitas");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB008_Categoria_Despesa", b =>
                {
                    b.Navigation("TB009_Tipo_Despesa");

                    b.Navigation("TB011_Despesas");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB011_Categoria_Produto_Compra", b =>
                {
                    b.Navigation("TB013_Item_Produto_Compras");
                });
#pragma warning restore 612, 618
        }
    }
}
