// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGFP.Infrastructure.Context;

#nullable disable

namespace SGFP.Infrastructure.Migrations
{
    [DbContext(typeof(AppSGPFContext))]
    partial class AppSGPFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SGFP.Domain.Entities.TB003_Categoria_Receita", b =>
                {
                    b.Property<int>("categoriaReceita_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIA_RECEITA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoriaReceita_Id"));

                    b.Property<string>("categoriaReceita_Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CATEGORIA_RECEITA_NOME");

                    b.HasKey("categoriaReceita_Id");

                    b.ToTable("TB003_CATEGORIA_RECEITA", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB004_Tipo_Origem_Dinheiro", b =>
                {
                    b.Property<int>("tipoOrigemDinheiro_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TIPO_ORIGEM_DINHEIRO_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tipoOrigemDinheiro_Id"));

                    b.Property<int>("categoriaReceita_Id")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIA_RECEITA_ID");

                    b.Property<string>("tipo_Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TIPO_DESCRICAO");

                    b.Property<string>("tipo_Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TIPO_NOME");

                    b.HasKey("tipoOrigemDinheiro_Id");

                    b.HasIndex("categoriaReceita_Id");

                    b.ToTable("TB004_TIPO_ORIGEM_DINHEIRO", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB005_Recebimento", b =>
                {
                    b.Property<int>("recebimento_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RECEBIMENTO_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("recebimento_Id"));

                    b.Property<string>("recebimento_Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RECEBIMENTO_DESCRICAO");

                    b.Property<string>("recebimento_Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RECEBIMENTO_NOME");

                    b.HasKey("recebimento_Id");

                    b.ToTable("TB005_RECEBIMENTO", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB006_Frequencia", b =>
                {
                    b.Property<int>("frequencia_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FREQUENCIA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("frequencia_Id"));

                    b.Property<string>("frequencia_Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FREQUENCIA_DESCRICAO");

                    b.Property<string>("frequencia_Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FREQUENCIA_NOME");

                    b.HasKey("frequencia_Id");

                    b.ToTable("TB006_FREQUENCIA", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB007_Receita", b =>
                {
                    b.Property<int>("receita_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RECEITA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("receita_Id"));

                    b.Property<bool>("ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ATIVO");

                    b.Property<DateTime>("data_Fim")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_FIM");

                    b.Property<DateTime>("data_Inicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_INICIO");

                    b.Property<int>("frequencia_Id")
                        .HasColumnType("int")
                        .HasColumnName("FREQUENCIA_ID");

                    b.Property<int>("recebimento_Id")
                        .HasColumnType("int")
                        .HasColumnName("RECEBIMENTO_ID");

                    b.Property<decimal>("receita_Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("RECEITA_VALOR");

                    b.Property<int>("tipo_Origem_Dinheiro_Id")
                        .HasColumnType("int")
                        .HasColumnName("TIPO_ORIGEM_DINHEIRO_ID");

                    b.Property<int>("usuario_Id")
                        .HasColumnType("int")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("receita_Id");

                    b.HasIndex("frequencia_Id");

                    b.HasIndex("recebimento_Id");

                    b.HasIndex("tipo_Origem_Dinheiro_Id");

                    b.ToTable("TB007_RECEITA", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB008_Categoria_Despesa", b =>
                {
                    b.Property<int>("categoria_Despesa_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIA_DESPESA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoria_Despesa_Id"));

                    b.Property<string>("categoria_Despesa_Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CATEGORIA_DESPESA_DESCRICAO");

                    b.Property<string>("categoria_Despesa_Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CATEGORIA_DESPESA_NOME");

                    b.HasKey("categoria_Despesa_Id");

                    b.ToTable("TB008_CATEGORIA_DESPESA", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB009_Tipo_Despesa", b =>
                {
                    b.Property<int>("tipo_Despesa_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TIPO_DESPESA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tipo_Despesa_Id"));

                    b.Property<int>("categoria_Despesa_Id")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIA_DESPESA_ID");

                    b.Property<string>("tipo_Despesa_Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TIPO_DESPESA_NOME");

                    b.HasKey("tipo_Despesa_Id");

                    b.HasIndex("categoria_Despesa_Id");

                    b.ToTable("TB009_TIPO_DESPESA", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB010_Despesa", b =>
                {
                    b.Property<int>("despesa_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DESPESA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("despesa_Id"));

                    b.Property<bool>("ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ATIVO");

                    b.Property<int>("categoria_Despesa_Id")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIA_DESPESA_ID");

                    b.Property<DateTime>("data_Fim")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_FIM");

                    b.Property<DateTime>("data_Inicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_INICIO");

                    b.Property<DateTime>("data_Vencimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_VENCIMENTO");

                    b.Property<string>("despesa_Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DESPESA_DESCRICAO");

                    b.Property<decimal>("despesa_Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DESPESA_VALOR");

                    b.Property<int>("frequencia_Id")
                        .HasColumnType("int")
                        .HasColumnName("FREQUENCIA_ID");

                    b.Property<int>("status_Pagamento_Id")
                        .HasMaxLength(255)
                        .HasColumnType("int")
                        .HasColumnName("STATUS_PAGAMENTO_ID");

                    b.Property<int>("usuario_Id")
                        .HasColumnType("int")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("despesa_Id");

                    b.HasIndex("categoria_Despesa_Id");

                    b.HasIndex("frequencia_Id");

                    b.HasIndex("status_Pagamento_Id");

                    b.ToTable("TB010_DESPESA", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB011_Categoria_Produto_Compra", b =>
                {
                    b.Property<int>("categoria_Produto_Compra_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIA_PRODUTO_COMPRA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoria_Produto_Compra_ID"));

                    b.Property<string>("categoria_Produto_Compra_Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CATEGORIA_PRODUTO_COMPRA_NOME");

                    b.HasKey("categoria_Produto_Compra_ID");

                    b.ToTable("TB011_CATEGORIA_PRODUTO_COMPRA", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB012_Unidade_Produto_Compra", b =>
                {
                    b.Property<int>("unidade_Produto_Compra_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UNIDADE_PRODUTO_COMPRA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("unidade_Produto_Compra_Id"));

                    b.Property<string>("unidade_Produto_Compra_Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UNIDADE_PRODUTO_COMPRA_NOME");

                    b.HasKey("unidade_Produto_Compra_Id");

                    b.ToTable("TB012_UNIDADE_PRODUTO_COMPRA", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB013_Item_Produto_Compra", b =>
                {
                    b.Property<int>("item_Produto_Compra_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ITEM_PRODUTO_COMPRA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("item_Produto_Compra_Id"));

                    b.Property<int>("categoria_Produto_Compra_ID")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIA_PRODUTO_COMPRA_ID");

                    b.Property<string>("item_Produto_Compra_Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ITEM_PRODUTO_COMPRA_NOME");

                    b.HasKey("item_Produto_Compra_Id");

                    b.HasIndex("categoria_Produto_Compra_ID");

                    b.ToTable("TB013_ITEM_PRODUTO_COMPRA", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB014_Item_Compra", b =>
                {
                    b.Property<int>("item_Compra_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ITEM_COMPRA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("item_Compra_Id"));

                    b.Property<int>("categoria_Produto_Compra_ID")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIA_PRODUTO_COMPRA_ID");

                    b.Property<DateTime>("item_Compra_Data_Compra")
                        .HasColumnType("datetime2")
                        .HasColumnName("ITEM_COMPRA_DATA_COMPRA");

                    b.Property<decimal>("item_Compra_Preco_Unitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ITEM_COMPRA_PRECO_UNITARIO");

                    b.Property<int>("item_Compra_Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("ITEM_COMPRA_QUANTIDADE");

                    b.Property<decimal>("item_Compra_Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ITEM_COMPRA_TOTAL");

                    b.Property<int>("item_Produto_Compra_Id")
                        .HasColumnType("int")
                        .HasColumnName("ITEM_PRODUTO_COMPRA_ID");

                    b.Property<int>("unidade_Produto_Compra_Id")
                        .HasColumnType("int")
                        .HasColumnName("UNIDADE_PRODUTO_COMPRA_ID");

                    b.Property<int>("usuario_Id")
                        .HasColumnType("int")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("item_Compra_Id");

                    b.HasIndex("categoria_Produto_Compra_ID");

                    b.HasIndex("item_Produto_Compra_Id");

                    b.HasIndex("unidade_Produto_Compra_Id");

                    b.ToTable("TB014_ITEM_COMPRA", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB015_Status_Pagamentos", b =>
                {
                    b.Property<int>("status_Pagamento_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("STATUS_PAGAMENTO_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("status_Pagamento_Id"));

                    b.Property<string>("status_Pagamento_Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STATUS_PAGAMENTO_NOME");

                    b.Property<bool>("status_Pagamento_Status")
                        .HasColumnType("bit")
                        .HasColumnName("STATUS_PAGAMENTO_STATUS");

                    b.HasKey("status_Pagamento_Id");

                    b.ToTable("TB015_STATUS_PAGAMENTO", (string)null);
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB004_Tipo_Origem_Dinheiro", b =>
                {
                    b.HasOne("SGFP.Domain.Entities.TB003_Categoria_Receita", "TB003_Categoria_Receita")
                        .WithMany("TB004_Tipo_Origem_Dinheiros")
                        .HasForeignKey("categoriaReceita_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TB003_Categoria_Receita");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB007_Receita", b =>
                {
                    b.HasOne("SGFP.Domain.Entities.TB006_Frequencia", "TB006_Frequencias")
                        .WithMany("TB007_Receitas")
                        .HasForeignKey("frequencia_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGFP.Domain.Entities.TB005_Recebimento", "TB005_Recebimentos")
                        .WithMany("TB007_Receitas")
                        .HasForeignKey("recebimento_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGFP.Domain.Entities.TB004_Tipo_Origem_Dinheiro", "TB004_Tipo_Origem_Dinheiros")
                        .WithMany("TB007_Receitas")
                        .HasForeignKey("tipo_Origem_Dinheiro_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TB004_Tipo_Origem_Dinheiros");

                    b.Navigation("TB005_Recebimentos");

                    b.Navigation("TB006_Frequencias");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB009_Tipo_Despesa", b =>
                {
                    b.HasOne("SGFP.Domain.Entities.TB008_Categoria_Despesa", "TB008_Categoria_Despesas")
                        .WithMany("TB009_Tipo_Despesa")
                        .HasForeignKey("categoria_Despesa_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TB008_Categoria_Despesas");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB010_Despesa", b =>
                {
                    b.HasOne("SGFP.Domain.Entities.TB008_Categoria_Despesa", "TB008_Categoria_Despesas")
                        .WithMany("TB010_Despesas")
                        .HasForeignKey("categoria_Despesa_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGFP.Domain.Entities.TB006_Frequencia", "TB006_Frequencia")
                        .WithMany("TB010_Despesas")
                        .HasForeignKey("frequencia_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGFP.Domain.Entities.TB015_Status_Pagamentos", "TB015_Status_Pagamento")
                        .WithMany("TB010_Despesas")
                        .HasForeignKey("status_Pagamento_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TB006_Frequencia");

                    b.Navigation("TB008_Categoria_Despesas");

                    b.Navigation("TB015_Status_Pagamento");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB013_Item_Produto_Compra", b =>
                {
                    b.HasOne("SGFP.Domain.Entities.TB011_Categoria_Produto_Compra", "TB011_Categoria_Produto_Compras")
                        .WithMany("TB013_Item_Produto_Compras")
                        .HasForeignKey("categoria_Produto_Compra_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TB011_Categoria_Produto_Compras");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB014_Item_Compra", b =>
                {
                    b.HasOne("SGFP.Domain.Entities.TB011_Categoria_Produto_Compra", "TB011_Categoria_Produto_Compras")
                        .WithMany("TB014_Item_Compras")
                        .HasForeignKey("categoria_Produto_Compra_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGFP.Domain.Entities.TB013_Item_Produto_Compra", "TB013_Item_Produto_Compra")
                        .WithMany("TB014_Item_Compras")
                        .HasForeignKey("item_Produto_Compra_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGFP.Domain.Entities.TB012_Unidade_Produto_Compra", "TB012_Unidade_Produto_Compras")
                        .WithMany("TB014_Item_Compras")
                        .HasForeignKey("unidade_Produto_Compra_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TB011_Categoria_Produto_Compras");

                    b.Navigation("TB012_Unidade_Produto_Compras");

                    b.Navigation("TB013_Item_Produto_Compra");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB003_Categoria_Receita", b =>
                {
                    b.Navigation("TB004_Tipo_Origem_Dinheiros");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB004_Tipo_Origem_Dinheiro", b =>
                {
                    b.Navigation("TB007_Receitas");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB005_Recebimento", b =>
                {
                    b.Navigation("TB007_Receitas");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB006_Frequencia", b =>
                {
                    b.Navigation("TB007_Receitas");

                    b.Navigation("TB010_Despesas");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB008_Categoria_Despesa", b =>
                {
                    b.Navigation("TB009_Tipo_Despesa");

                    b.Navigation("TB010_Despesas");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB011_Categoria_Produto_Compra", b =>
                {
                    b.Navigation("TB013_Item_Produto_Compras");

                    b.Navigation("TB014_Item_Compras");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB012_Unidade_Produto_Compra", b =>
                {
                    b.Navigation("TB014_Item_Compras");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB013_Item_Produto_Compra", b =>
                {
                    b.Navigation("TB014_Item_Compras");
                });

            modelBuilder.Entity("SGFP.Domain.Entities.TB015_Status_Pagamentos", b =>
                {
                    b.Navigation("TB010_Despesas");
                });
#pragma warning restore 612, 618
        }
    }
}
